name: Actions Workflow

on: [push]

env:
  WF_ENV: WF_ENV1

jobs:
  running-actions:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: JOB_ENV
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Observing Environmental variables
        env:
          STEP_ENV: STEP_ENV
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_ACTION
          echo $GITHUB_ACTIONS
          echo $GITHUB_ACTOR
          echo $GITHUB_REF
          echo $WF_ENV
          echo $JOB_ENV
          echo $STEP_ENV