name: Basic Shell Commands

on:
  repository_dispatch:
    # types: [build]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Simple Github action!"
      - name: multiline script example
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
      - name: Echo client payload
        run: echo "${{ github.event.client_payload.env }}"
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Powershell fetch directory
        run: Get-Location
      - name: Bash fetch directory
        run: pwd
        shell: bash
